dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.7.2
  - fx-portal/contracts@1.0.4
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.2'
      - '@fxportal=fx-portal/contracts@1.0.4'

dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
  test1: ${T1}
  test2: ${T2}
  test3: ${T3}
  test4: ${T4}
  test5: ${T5}
  test6: ${T6}
  test7: ${T7}
  test8: ${T8}
  test9: ${T9}

networks:
  goerli:
    verify: True
    checkpoint_manager: '0x2890bA17EfE978480615e330ecB65333b880928e'
    fx_root: '0x3d1d3E34f7fB6D26245E6640E1c50710eFFf15bA'
  mainnet:
    verify: True
  polygon-test:
    verify: True
    fx_child: '0xCf73231F28B7331BBe3124B907840A94851f9f11'
